# Generated by Django 6.0.6 on 2026-06-25 09:31

import employees.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='joining_date',
            field=models.DateField(validators=[employees.models.validate_joining_date]),
        ),
    ]
