# Generated by Django 6.0.6 on 2026-07-03 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_blockedip_ip_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='emoloyee_id',
            new_name='employee_id',
        ),
        migrations.AlterField(
            model_name='blockedip',
            name='ip_address',
            field=models.GenericIPAddressField(),
        ),
    ]
