# Generated by Django 6.0.6 on 2026-07-08 08:31

import employees.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_employee_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='aadhaar_document',
            field=models.FileField(blank=True, null=True, upload_to='employees/documents/aadhaar/', validators=[employees.validators.validate_file_size, employees.validators.validate_pdf_extension]),
        ),
        migrations.AddField(
            model_name='employee',
            name='pan_document',
            field=models.FileField(blank=True, null=True, upload_to='employees/documents/pan/', validators=[employees.validators.validate_file_size, employees.validators.validate_pdf_extension]),
        ),
        migrations.AddField(
            model_name='employee',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='employees/profile_photos/', validators=[employees.validators.validate_file_size, employees.validators.validate_image_extension]),
        ),
        migrations.AddField(
            model_name='employee',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='employees/resumes/', validators=[employees.validators.validate_file_size, employees.validators.validate_pdf_extension]),
        ),
    ]
