# Generated by Django 6.0.6 on 2026-07-08 10:03

import django.db.models.deletion
import employees.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_employee_aadhaar_document_employee_pan_document_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('resume', 'Resume'), ('pan', 'PAN'), ('aadhaar', 'Aadhaar'), ('degree', 'Degree Certificate'), ('experience', 'Experience Certificate'), ('offer', 'Offer')], max_length=50)),
                ('file', models.FileField(upload_to='documents/', validators=[employees.validators.validate_file_size, employees.validators.validate_pdf_extension])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='employees.employee')),
            ],
        ),
    ]
