# Generated by Django 6.0.7 on 2026-07-24 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('SICK', 'Sick Leave'), ('CASUAL', 'Casual Leave'), ('EARNED', 'Earned Leave'), ('OTHER', 'Other Leave')], max_length=20)),
                ('reason', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING_MANAGER', 'Pending Manager Approval'), ('PENDING_HR', 'Pending HR Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING_MANAGER', max_length=30)),
                ('manager_comment', models.TextField(blank=True, null=True)),
                ('hr_comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='employees.employee')),
            ],
        ),
    ]
