# Generated by Django 6.0.6 on 2026-06-23 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_employee_id_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('HR', 'HR'), ('manager', 'Manager'), ('employee', 'Employee')], max_length=20),
        ),
    ]
