# Generated by Django 6.0.7 on 2026-07-26 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('EMPLOYEE', 'Employee Report'), ('ATTENDANCE', 'Attendance Report'), ('LEAVE', 'Leave Report'), ('PAYROLL', 'Payroll Report')], max_length=50)),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
