# Generated by Django 6.0.7 on 2026-07-30 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendance_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='joining_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
